### ISSUE TITLE
Make render async

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/jsx-md#1]
At the moment, the full rendering process is synchronous. This prevents us from writing components that fetch data asynchronously, e. g. via a web request. Since markdown is only used for one-off rendering without any interactivity, we don't have to worry about loading states. Therefore we can find a simple solution for asynchronous rendering.

## Describe the solution you'd like

Make `render` asynchronous, so that it renders the existing components as before.

## Describe alternatives you've considered

React uses hooks and state to manage asynchronous rendering. This seems to be too complicated for this usecase, though.

## Additional context

This is preparation for #2

**Comment by KwanJunWen** [comment]
Hi, I am interested on this issue, can I try this ?

**Comment by dbartholomae** [comment]
Hi! I've already started on this since no one seemed to have noticed the repo, but if you are interested I could wrap up my refactors next week and then next weekend you could take over :)
