### ISSUE TITLE
feat(Task): Create a Task Component

### ISSUE THREAD

**Issue by KwanJunWen** [dbartholomae/jsx-md#2]
Sometimes we would want to write a check list in markdown. Having a TaskList component allows users to create task list using JSX.

## Would you be willing to help with a PR? 
[X] Yes, absolutely
[ ] Yes, with some guidance
[ ] Unfortunately no time :'-(

## Describe the solution you'd like
The markdown element could be created with the following 
```jsx
<TaskList tasks={tasks}  />
```
Each task should have a boolean that indicates whether if the task is checked.

## Additional context
Refer to [this](https://www.markdownguide.org/extended-syntax/#task-lists) for additional context.

**Comment by dbartholomae** [comment]
Tasklist is something like this?

```
[X] Test tasks
[ ] Become immortal
```

If so: I don't think this is actually supported in most Markdown versions - e. g. Gists don't render these.

**Comment by dbartholomae** [comment]
Ah, it's

- [x] Test tasks
- [ ] Become immortal

Sounds good! I would suggest the following JSX though:

```jsx
<Task checked>Test tasks</Task>
<Task>Become immortal</Task>
```

**Comment by KwanJunWen** [comment]
Sorry to bother as this is probably off-topic. This is my first time participating hacktoberfest and I am wondering whether if all the PRs that I've contributed will count towards hacktoberfest or not. Based on the requirements, it states that the repository need to have the `hacktoberfest` topic to be considered an eligible repository.

**Comment by dbartholomae** [comment]
@KwanJunWen I've already added the topic, so each PR should be eliglible. If you log into your profile at https://hacktoberfest.digitalocean.com/ you should be able to see details around this. If there is any problems, please let me know :)
