### ISSUE TITLE
feat(Table): Add alignment options for body 

### ISSUE THREAD

**Issue by KwanJunWen** [dbartholomae/jsx-md#3]
The current table component does not seem to support text alignment yet. We could improve the component by adding the alignment option.

## Would you be willing to help with a PR?
[X] Yes, absolutely
[ ] Yes, with some guidance
[ ] Unfortunately no time :'-(

## Describe the solution you'd like
Probably have to add another props that defines the alignment for the table body. Will default to current rendering if alignment is not provided.

## Additional context
Can refer to [this](https://www.markdownguide.org/extended-syntax/#alignment) for more context.

**Comment by dbartholomae** [comment]
I like the idea! What would this look like in JSX?

**Comment by KwanJunWen** [comment]
I was thinking about something like: 
```jsx
const headers = {
  foo: "Foo header",
  bar: "Bar header",
};
const body = [
  { foo: "Foo body 1", bar: "Bar body 1" },
  { foo: "Foo body 2", bar: "Bar body 2" },
];
const alignment = {
   foo: 'center',
   bar: 'right',
};
<Table headers={headers} body={body} alignment={alignment} />
```
`alignment` prop expects an object similar to `headers`, but with either `left`, `center` or `right` string value. If not provided, will default to `left`.
