### ISSUE TITLE
refactor(Emphasize): Emphasize API refactor proposal

### ISSUE THREAD

**Issue by KwanJunWen** [dbartholomae/jsx-md#5]
The `Emphasize` component renders italic style by default, and bold if `strong` prop is set to true. When we want to render a bold and italic text, we have to wrap Emphasize component twice, with each set to strong and another without.

** Would you be willing to help with a PR? **
[X] Yes, absolutely
[ ] Yes, with some guidance
[ ] Unfortunately no time :'-(

## Describe the solution you'd like
Instead, `Emphasize` component will not do anything to the text by default, set `strong` prop to true to wrap the content with `**`, and set `italic` prop to true to wrap the content with `*`. Since `_` shouldn't be used in the middle of a word, it is safer to only use `*`.

## Additional context
Best practices references.
[Bold](https://www.markdownguide.org/basic-syntax#bold-best-practices)
[Italic](https://www.markdownguide.org/basic-syntax#italic-best-practices)

**Comment by dbartholomae** [comment]
In that case, what would `<Emphasize>Text</Emphasize>` look like?

I would suggest to add `<Bold>` and `<Italics>` and deprecate `<Emphasize>` instead. But please continue the existing use of `<Italics>Test</Italics>` being `_Test_` and `<Bold>Test</Bold>` being `**Test**` as this is what `prettier` changes markdown to.
