### ISSUE TITLE
Add Promise element

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/jsx-md#9]
At the moment, each element is created synchronously. This prevents us from writing components that fetch data asynchronously, e. g. via a web request. Since markdown is only used for one-off rendering without any interactivity, we don't have to worry about loading states. Therefore we can find a simple solution for asynchronous rendering.

## Describe the solution you'd like

Add a new `md-promise` element which accepts a `Promise` as `children`. Please add a `Promise` element similar to how `Fragment` wraps `md-fragment`.
This should render by resolving the promise. If the promise rejects, reject with the same error.

If you get stuck working on this, I am [available for pair programming](https://calendly.com/bartholomae/open-source-pair-programming).

## Describe alternatives you've considered

React uses hooks and state to manage asynchronous rendering. This seems to be too complicated for this usecase, though.

## Additional context
 
This is based on the breaking change done in #1 so that this change itself no longer is breaking.

When this issue is resolved, we can add additional functionality to [jsx-readme](https://github.com/dbartholomae/jsx-readme) that uses information from the GitHub API to e. g. add an up-to-date list of contributors.

**Comment by dbartholomae** [comment]
@KwanJunWen this is the new issue based on the changes I merged in #10 
Feel free to take it :)

**Comment by junwen-k** [comment]
@dbartholomae Hi, this is another account of @KwanJunWen. I will take on this one :)
